<?php

    require 'verifica_usuario.php';

    session_start();
    if (isset($_SESSION['esta_logado']) == false OR $_SESSION['esta_logado'] == false) {

        //usuario nao logado
        header('Location: login.php');
    }
?>
<?php

    require 'controlador_agenda.php';

    if (isset($_GET['buscar']) && !empty($_GET['buscar'])){
        $meusContatos = buscarContato($_GET['buscar']);
    }else{
        $meusContatos = json();
    }


?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Agenda</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <style>
        #editar{
            color: forestgreen;
        }
        #excluir{
            color: red;
        }
        #aaa{
            color: transparent;
        }
        #a{
            border-bottom: 10px;
            border-top: 10px;
        }
        

    </style>


</head>
<body>




	<div class="container" style="margin-top: 30px;">

		<h3>MINHA AGENDA DE CONTATOS</h3>
		<br />

        <a id="sair" href="verifica_usuario.php?acao=sair" class="btn btn-danger">SAIR</a>


		<!-- CADASTRO-->
		<div class="row">

            <div align="center">
                <form id="a" class="form-inline" method="get" action="">
                    <!--Campo de busca-->
                    <div class="form-group">
                        <input name="buscar" type="text" class="form-control" id="buscar">
                        <button type="submit">Buscar</button>
                    </div>
                </form>
            </div>


            <div class="col-md-12">
				<form class="form-inline" method="post" action="controlador_agenda.php?acao=cadastrar">
				  
				  <!--nome-->
				  <div class="form-group">
				    <label for="nome">Nome</label>
				    <input name="nome" type="text" class="form-control" id="nome">
				  </div>
				  
				  <!--email-->
				  <div class="form-group">
				    <label for="email">Email</label>
				    <input name="email" type="email" class="form-control" id="email">
				  </div>

				  <!--telefone-->
				  <div class="form-group">
				    <label for="telefone">Telefone</label>
				    <input name="telefone" type="text" class="form-control" id="telefone">
				  </div>
				  
				  <button type="submit" class="btn btn-danger">CADASTRAR</button>

				</form>
			</div>
		</div>

		<br />
		
		<!--CONTATOS-->
		<div class="row">
			<div class="col-md-12">

				<!-- Conteúdo -->
				<table class="table"> 
					<thead> 
						<tr> 
							<th>#</th> 
							<th>Nome</th> 
							<th>Email</th> 
							<th>Telefone</th>
                            <th>Ações</th>
						</tr> 
					</thead> 
					<tbody>
						<!-- repetir -->
                        <?php foreach($meusContatos as $contato): ?>
						<tr>
							<td><?= $contato['id'] ?></td>
							<td><?= $contato['nome'] ?></td>
							<td><?= $contato['email'] ?></td>
							<td><?= $contato['telefone'] ?></td>
                            <td>
                                <a href="controlador_agenda.php?acao=excluir&id=<?= $contato['id'] ?>"><i id="excluir" class="fa fa-times" aria-hidden="true"></i></a>
                                <i id="aaa">a</i>
                                <a href="editar.php?id=<?= $contato['id'] ?>"><i class="fa fa-pencil-square-o" aria-hidden="true" id="editar"></i></a>
                            </td>
						</tr>
                        <?php endforeach; ?>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</body>
</html>
